spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpaplayground
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      pool-name: jpasamples

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 0
        generate_statistics: false

logging:
  level:
    root: info
    org.gol: info