version: "3.4"
services:

  postgres:
    image: postgres:14.5
    command: postgres -c 'max_connections=200'
    container_name: jpasamples-postgres
    environment:
      - POSTGRES_DB=jpasamples
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ../storage/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: jpasamples-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.dev
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5480:80"

